mv 01d.svg clearsky_day.svg
mv 01n.svg clearsky_night.svg
mv 01m.svg clearsky_polartwilight.svg
mv 02d.svg fair_day.svg
mv 02n.svg fair_night.svg
mv 02m.svg fair_polartwilight.svg
mv 03d.svg partlycloudy_day.svg
mv 03n.svg partlycloudy_night.svg
mv 03m.svg partlycloudy_polartwilight.svg
mv 04.svg cloudy.svg
mv 05d.svg rainshowers_day.svg
mv 05n.svg rainshowers_night.svg
mv 05m.svg rainshowers_polartwilight.svg
mv 06d.svg rainshowersandthunder_day.svg
mv 06n.svg rainshowersandthunder_night.svg
mv 06m.svg rainshowersandthunder_polartwilight.svg
mv 07d.svg sleetshowers_day.svg
mv 07n.svg sleetshowers_night.svg
mv 07m.svg sleetshowers_polartwilight.svg
mv 08d.svg snowshowers_day.svg
mv 08n.svg snowshowers_night.svg
mv 08m.svg snowshowers_polartwilight.svg
mv 09.svg rain.svg
mv 10.svg heavyrain.svg
mv 11.svg heavyrainandthunder.svg
mv 12.svg sleet.svg
mv 13.svg snow.svg
mv 14.svg snowandthunder.svg
mv 15.svg fog.svg
mv 20d.svg sleetshowersandthunder_day.svg
mv 20n.svg sleetshowersandthunder_night.svg
mv 20m.svg sleetshowersandthunder_polartwilight.svg
mv 21d.svg snowshowersandthunder_day.svg
mv 21n.svg snowshowersandthunder_night.svg
mv 21m.svg snowshowersandthunder_polartwilight.svg
mv 22.svg rainandthunder.svg
mv 23.svg sleetandthunder.svg
mv 24d.svg lightrainshowersandthunder_day.svg
mv 24n.svg lightrainshowersandthunder_night.svg
mv 24m.svg lightrainshowersandthunder_polartwilight.svg
mv 25d.svg heavyrainshowersandthunder_day.svg
mv 25n.svg heavyrainshowersandthunder_night.svg
mv 25m.svg heavyrainshowersandthunder_polartwilight.svg
mv 26d.svg lightssleetshowersandthunder_day.svg
mv 26n.svg lightssleetshowersandthunder_night.svg
mv 26m.svg lightssleetshowersandthunder_polartwilight.svg
mv 27d.svg heavysleetshowersandthunder_day.svg
mv 27n.svg heavysleetshowersandthunder_night.svg
mv 27m.svg heavysleetshowersandthunder_polartwilight.svg
mv 28d.svg lightssnowshowersandthunder_day.svg
mv 28n.svg lightssnowshowersandthunder_night.svg
mv 28m.svg lightssnowshowersandthunder_polartwilight.svg
mv 29d.svg heavysnowshowersandthunder_day.svg
mv 29n.svg heavysnowshowersandthunder_night.svg
mv 29m.svg heavysnowshowersandthunder_polartwilight.svg
mv 30.svg lightrainandthunder.svg
mv 31.svg lightsleetandthunder.svg
mv 32.svg heavysleetandthunder.svg
mv 33.svg lightsnowandthunder.svg
mv 34.svg heavysnowandthunder.svg
mv 40d.svg lightrainshowers_day.svg
mv 40n.svg lightrainshowers_night.svg
mv 40m.svg lightrainshowers_polartwilight.svg
mv 41d.svg heavyrainshowers_day.svg
mv 41n.svg heavyrainshowers_night.svg
mv 41m.svg heavyrainshowers_polartwilight.svg
mv 42d.svg lightsleetshowers_day.svg
mv 42n.svg lightsleetshowers_night.svg
mv 42m.svg lightsleetshowers_polartwilight.svg
mv 43d.svg heavysleetshowers_day.svg
mv 43n.svg heavysleetshowers_night.svg
mv 43m.svg heavysleetshowers_polartwilight.svg
mv 44d.svg lightsnowshowers_day.svg
mv 44n.svg lightsnowshowers_night.svg
mv 44m.svg lightsnowshowers_polartwilight.svg
mv 45d.svg heavysnowshowers_day.svg
mv 45n.svg heavysnowshowers_night.svg
mv 45m.svg heavysnowshowers_polartwilight.svg
mv 46.svg lightrain.svg
mv 47.svg lightsleet.svg
mv 48.svg heavysleet.svg
mv 49.svg lightsnow.svg
mv 50.svg heavysnow.svg
